name: Deploy

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: ${{ github.event_name == 'push' && !contains($COMMIT_MESSAGES, 'skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "testingworkflows" #Must be unique in Heroku
          heroku_email: "ika.bidzishvili@gmail.com"
          healthcheck: "https://testingworkflows.herokuapp.com/health"
